# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'andrii_bilan_SimplePins' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for andrii_bilan_SimplePins
	pod 'FBSDKLoginKit', :inhibit_warnings => true
end
